### ISSUE TITLE
Repace Tensorflow modules w/ DeepJavaLIbrary

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-functions-catalog#20]
It looks like Tensorflow Java support has changed significantly: https://www.tensorflow.org/jvm/install.

With our new Functions Catalog version it is good timing to look into keeping everything up-to-date.

**Comment by onobc** [comment]
@tzolov did some digging on this and updating to TF 2.0 will require quite a bit of effort. 

In the meantime, we have removed the current TF 1.0 based modules in [this commit](https://github.com/spring-cloud/spring-functions-catalog/commit/0f65110e89164cf5e67999dfa38bbdd9ff7578c8).

The intention is to re-implement the `ImageRecognition/ObjectDetection/Segmentation` as Functions, but using [DeepJavaLibrary](https://docs.djl.ai/) rather than TF 2.0. The motivation is that it will bring more flexibility/capability with less maintenance cost.
