### ISSUE TITLE
Update org.apache.avro:avro to fix CVE-2024-47561

### ISSUE THREAD

**Issue by dxxbbf** [spring-cloud/spring-functions-catalog#84]
**In what version(s) of Spring Functions Catalog are you seeing this issue?**

`spring-debezium-supplier:5.0.0`

**Describe the bug**

spring-debezium-supplier depends on `org.apache.avro:avro` on version [1.11.3](https://github.com/spring-cloud/spring-functions-catalog/blob/main/supplier/spring-debezium-supplier/build.gradle#L10). This version is affected by https://nvd.nist.gov/vuln/detail/CVE-2024-47561.

Please update `org.apache.avro:avro` to at least `1.11.4` or `1.12.0`.

Maybe you could implement something like renovatebot or depandabot to do updates like this automatic.

**Comment by artembilan** [comment]
See content of the `build.gradle` for that Debezium Supplier: https://github.com/spring-cloud/spring-functions-catalog/blob/main/supplier/spring-debezium-supplier/build.gradle.

So, whatever we have there so far is something temporal.
Plus we do use Dependabot in the project: https://github.com/spring-cloud/spring-functions-catalog/blob/main/.github/dependabot.yml.
But it is not able to see Gradle scripts in the sub-projects according to its `directory` option: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory.

We probably need to look into [directories](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories) instead with a `**/*`.

I'll double check shortly if we still need those deps to manage since we have upgraded to Debezium `2.6.2` since then.

**Comment by artembilan** [comment]
OK. The `io.debezium:debezium-bom` brings for us an outdated `io.apicurio:apicurio-registry-utils-converter`, which pulls an outdated `org.apache.avro:avro` yet.
So, we don't have choice but still support those deps explicitly.

We may think about cutting version `5.1` where we would really upgrade to the latest, less vulnerable deps.
For the current `5.0.1`, we don't have choice but just update that `org.apache.avro:avro` to the mentioned `1.11.4`.

I'll see if Dependabot will be able to do the trick for us with its `directories` option.

**Comment by artembilan** [comment]
Looks like that works: https://github.com/spring-cloud/spring-functions-catalog/pull/90 !

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-cloud/spring-functions-catalog/commit/ce5e512ce156d15431d6de13ce47aa98a16c8643

**Comment by dxxbbf** [comment]
That looks great, thanks for your quick fix! 
When do you plan to do a new release for `spring-debezium-supplier`?

**Comment by artembilan** [comment]
Thanks for confirmation ! We will discuss with the team, but in my feeling somewhere in the end of month, when all other Spring projects are done with their releases.
